<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7ARKDEF" failures="1" tests="7" name="com.qa.amazon.testcases.LoginPageTest" time="332.112" errors="0" timestamp="24 Sep. 2020 18:35:12 GMT" skipped="0">
  <testcase classname="com.qa.amazon.testcases.LoginPageTest" name="verifyLoginPageTitleTest" time="46.033">
    <failure message="expected [Amazon Sign Ins] but found [Amazon Sign In]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Amazon Sign Ins] but found [Amazon Sign In]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.amazon.testcases.LoginPageTest.verifyLoginPageTitleTest(LoginPageTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- verifyLoginPageTitleTest -->
  <testcase classname="com.qa.amazon.testcases.LoginPageTest" name="verifyLoginPageLogoTest" time="43.959"/>
  <testcase classname="com.qa.amazon.testcases.LoginPageTest" name="verifyConditionOfUseLinkTest" time="41.475"/>
  <testcase classname="com.qa.amazon.testcases.LoginPageTest" name="verifyNeedHelpLinkTest" time="37.043"/>
  <testcase classname="com.qa.amazon.testcases.LoginPageTest" name="verifyPrivacyNoticeLinkTest" time="41.046"/>
  <testcase classname="com.qa.amazon.testcases.LoginPageTest" name="verifyCreateAccountSubmitTest" time="44.010"/>
  <testcase classname="com.qa.amazon.testcases.LoginPageTest" name="verifyEnterEmailAddress" time="78.546"/>
</testsuite> <!-- com.qa.amazon.testcases.LoginPageTest -->
